<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/models/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.models.'), function () {

Route::get('vacations', ['as'=> 'vacations.index', 'uses' => 'Models\VacationController@index']);
Route::post('vacations', ['as'=> 'vacations.store', 'uses' => 'Models\VacationController@store']);
Route::get('vacations/create', ['as'=> 'vacations.create', 'uses' => 'Models\VacationController@create']);
Route::put('vacations/{vacations}', ['as'=> 'vacations.update', 'uses' => 'Models\VacationController@update']);
Route::patch('vacations/{vacations}', ['as'=> 'vacations.update', 'uses' => 'Models\VacationController@update']);
Route::get('vacations/{id}/delete', array('as' => 'vacations.delete', 'uses' => 'Models\VacationController@getDelete'));
Route::get('vacations/{id}/confirm-delete', array('as' => 'vacations.confirm-delete', 'uses' => 'Models\VacationController@getModalDelete'));
Route::get('vacations/{vacations}', ['as'=> 'vacations.show', 'uses' => 'Models\VacationController@show']);
Route::get('vacations/{vacations}/edit', ['as'=> 'vacations.edit', 'uses' => 'Models\VacationController@edit']);

});


Route::group(array('prefix' => 'admin/models/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.models.'), function () {

Route::get('holidays', ['as'=> 'holidays.index', 'uses' => 'Models\HolidayController@index']);
Route::post('holidays', ['as'=> 'holidays.store', 'uses' => 'Models\HolidayController@store']);
Route::get('holidays/create', ['as'=> 'holidays.create', 'uses' => 'Models\HolidayController@create']);
Route::put('holidays/{holidays}', ['as'=> 'holidays.update', 'uses' => 'Models\HolidayController@update']);
Route::patch('holidays/{holidays}', ['as'=> 'holidays.update', 'uses' => 'Models\HolidayController@update']);
Route::get('holidays/{id}/delete', array('as' => 'holidays.delete', 'uses' => 'Models\HolidayController@getDelete'));
Route::get('holidays/{id}/confirm-delete', array('as' => 'holidays.confirm-delete', 'uses' => 'Models\HolidayController@getModalDelete'));
Route::get('holidays/{holidays}', ['as'=> 'holidays.show', 'uses' => 'Models\HolidayController@show']);
Route::get('holidays/{holidays}/edit', ['as'=> 'holidays.edit', 'uses' => 'Models\HolidayController@edit']);

});
